// import type { Metadata } from "next";

// import "./globals.css";
// import { ThemeProvider } from '@emotion/react'
// import NavBar from "@/components/NavBar/NavBar";



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body >
//       <NavBar/>
//         {children}
        
//         </body>
//     </html>
//   );
// }
"use client"
import { ThemeProvider } from '@emotion/react';
import NavBar from "@/components/NavBar/NavBar";

const theme = {
  fonts: {
    body: "'Protest Guerrilla', sans-serif", 
    heading: "'Protest Guerrilla', sans-serif", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider theme={theme}>
      <html lang="en">
        <head>
          <link href="https://fonts.googleapis.com/css2?family=Protest+Guerrilla&display=swap" rel="stylesheet" />
        </head>
        <body>
          <NavBar />
          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
